name: "tests"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: "self-hosted"

    steps:
      - uses: actions/checkout@v3
      - name: "Set up Python 3.10.12"
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"
      - name: "Invoke Dependency Installs"
        run: |
          echo -e "Current working directory: $(pwd)"
          echo -e "--------- Directory Contents ---------\n"
          ls -la
          echo -e "\n--------- Directory Contents ---------"

          echo -e "\nInstall package dependencies started...\n"
          python3 -m pip install --upgrade pip

          pip3 install wheel

          if [ -f requirements-dev.txt ]; then pip3 install -r requirements-dev.txt; fi
          if [ -d ./redist ]; then pip3 install ./redist/*; fi

          pip3 install -e .

          echo -e "\nInstall package dependencies completed."
      - name: "Invoke Linting"
        run: |
          ruff .
      - name: "Invoke Tests"
        run: |
          pytest
